# Generated by Django 4.2.7 on 2026-04-26 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('wh_per_token', models.FloatField(help_text='Wh per token (Samsi et al 2023)')),
                ('context_window', models.IntegerField(default=128000)),
                ('released_year', models.IntegerField(blank=True, null=True)),
                ('params_billions', models.FloatField(blank=True, help_text='Parameter count in billions', null=True)),
                ('training_co2_kg', models.FloatField(blank=True, help_text='Training CO2e kg (Patterson et al 2021 / Sharma 2025)', null=True)),
                ('model_type', models.CharField(choices=[('dense', 'Dense'), ('moe', 'MoE'), ('other', 'Other')], default='dense', max_length=20)),
            ],
            options={
                'ordering': ['provider', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='CarbonRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, unique=True)),
                ('region_code', models.CharField(max_length=10, unique=True)),
                ('carbon_intensity_kg_kwh', models.FloatField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('year_recorded', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'ordering': ['carbon_intensity_kg_kwh'],
            },
        ),
        migrations.CreateModel(
            name='HardwareSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('tdp_watts', models.FloatField(help_text='Thermal Design Power in Watts')),
                ('fp16_tflops', models.FloatField(blank=True, null=True)),
                ('int8_tflops', models.FloatField(blank=True, null=True)),
                ('memory_gb', models.FloatField(blank=True, null=True)),
                ('embodied_co2_kg', models.FloatField(default=0, help_text='Manufacturing CO2e (Faiz et al 2024)')),
                ('released_year', models.IntegerField(blank=True, null=True)),
                ('hardware_type', models.CharField(choices=[('GPU', 'GPU'), ('TPU', 'TPU'), ('CPU', 'CPU')], default='GPU', max_length=20)),
            ],
            options={
                'ordering': ['manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('energy_mult', models.FloatField(default=1.0, help_text='Multiplier vs baseline inference')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecisionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('energy_factor', models.FloatField(default=1.0, help_text='Energy factor vs FP32 baseline')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('monthly_budget_g', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromptSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prompt_text', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.aimodel')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.carbonregion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptEmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_count', models.IntegerField(default=0)),
                ('energy_wh', models.FloatField(default=0)),
                ('co2_grams', models.FloatField(default=0)),
                ('co2_mg', models.FloatField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='calculator.promptsession')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_gpus', models.IntegerField(default=1)),
                ('duration_hrs', models.FloatField(default=1.0)),
                ('energy_kwh', models.FloatField(default=0)),
                ('co2_kg', models.FloatField(default=0)),
                ('cost_gbp', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.aimodel')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.hardwarespec')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.operationtype')),
                ('precision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.precisiontype')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.carbonregion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hw_calcs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('tag', models.CharField(choices=[('results', 'Results'), ('question', 'Question'), ('tip', 'Tip'), ('discussion', 'Discussion')], default='discussion', max_length=20)),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='calculator.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
